### ISSUE TITLE
Context "I am logged in as an administrator" failing

### ISSUE THREAD

**Issue by chougron** [Sylius/PluginSkeleton#128]
After installing a new project, and launching all the commands, then running the behat tests with Selenium, the context "I am logged in as an administrator" doesn't seem to be working.

I can see that a user is created in the database, but I am not logged in : the 3 example scenarios accessing the admin part of the website are failing because I am redirected to the login page.

`Expected to be on "http://localhost:8080/admin/products/new/simple" but found "http://localhost:8080/admin/login" instead (Sylius\Behat\Page\UnexpectedPageException)`

Is there a configuration that I am missing somewhere ? For the sessions ? The cache ? Something else ? The weird thing is that if I launch the website on http://localhost:8080, I can log in, and go to the given pages without problem.

**Comment by Zales0123** [comment]
Thank you, Camille, for reporting this, let the discuss happen in https://github.com/Sylius/PluginSkeleton/issues/138 :)
