### ISSUE TITLE
Less strict about Sylius version

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/PluginSkeleton#130]
Current installation requires `"sylius/sylius": "~1.4.0@dev",`. Can't that just be that latest supported Sylius version? In that case plugin developers take a wider range of Sylius versions in mind (also should maybe be tested against in Travis), and not only using latest versions. Makes plugins available to a bigger group of developers.

**Comment by stefandoorn** [comment]
E.g. if you change a plugin that started at 1.2.x to ^1.1, all fails now due to changes in 1.3.. Probably the test setup needs to be 1.3 compatible, while the src folder can be 1.1 compatible then.

**Comment by pamil** [comment]
There are some BC breaks regarding the CI setup mostly, let's keep the discussion in #104, since allowing testing multiple versions of Sylius at the same time will make it possible to loosen this constraint.
