### ISSUE TITLE
Upgrade MD to 1.3 links to file diffs don't show the specific diff of single file

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/PluginSkeleton#131]
E.g. https://github.com/Sylius/PluginSkeleton/compare/1.2...1.3#diff-726e1353c14df7d91379c0dea6b30eef

**Comment by stefandoorn** [comment]
Tried to fix this, but the URL that points to this specific file doesn't give the expected result (issue of GH) and it's the same as already in the UPGRADE file. So, not really solveable.. :(

**Comment by pamil** [comment]
@stefandoorn it can be done by opening a PR and referencing to its changeset, #135 :)
