### ISSUE TITLE
Use the .env file everywhere (and not the .env.test)

### ISSUE THREAD

**Issue by mmenozzi** [Sylius/PluginSkeleton#132]
Hi guys,
I think that we should use the `.env` file inside `tests/Application` as the only `.env` file used both for CI and for development.

Currently, if we want to use `.env` files, to make the plugin work locally we need to copy `.env.test.dist` to `.env.test` and to `.env`  (we don't want to do `set -a && source tests/Application/.env.test && set +a` locally).  Then in the `.env` file we can do our changes (for example use a SQLite DB).

I propose to change the following line:

https://github.com/Sylius/PluginSkeleton/blob/c08494520e1bd10bdf10b8bddc8029d4f7d63938/behat.yml.dist#L13

to:

`env_file: tests/Application/.env`

It this way we can remove `set -a && source tests/Application/.env.test && set +a` from the `.travis.yml` file and then also remove all the `-e test` from all the commands in  the README.

What do you think?

**Comment by stefandoorn** [comment]
Current plugin's still using the old skeleton fail on 1.2 due to this. I would vote indeed for a single .env file in this case, as it's rather clear that the application is solely for CI/test purposes in there.

**Comment by mmenozzi** [comment]
Yes @stefandoorn my proposal is relevant only for the new 1.3 skeleton.
@pamil do you want me to make the PR or do you want to wait for other comments?

**Comment by mmenozzi** [comment]
See the “contributing” paragraph of our plugin readme where we already applied this change: https://github.com/webgriffe/WebgriffeSyliusTableRateShippingPlugin/blob/master/README.md

**Comment by pamil** [comment]
Trying to go through those old issues here, I guess the issue is due to SymfonyExtension v1 being used at that time. Could you open a new one if it still exists with the more recent versions of PluginSkeleton?
