### ISSUE TITLE
Command not found: bin/console

### ISSUE THREAD

**Issue by Konafets** [Sylius/PluginSkeleton#142]
The README mentioned to execute the `bin/console` command to install the assets. However the command was not found because it is not executable by default. Add `chmod +x bin/console` to the README file.

**Comment by Zales0123** [comment]
`bin/console` is placed in `tests/Application`, therefore you should run `(cd tests/Application && bin/console {some-commmand})` always (e.g. `(cd tests/Application && bin/console assets:install public -e test)`)
