### ISSUE TITLE
[RFC] Move tests classes to autoload-dev

### ISSUE THREAD

**Issue by mmenozzi** [Sylius/PluginSkeleton#174]
I think that tests classes should be moved to `autoload-dev`:
https://github.com/Sylius/PluginSkeleton/blob/821a460a22e122c5e20e16f4e371d1be663a5ce1/composer.json#L48

Am I right?

**Comment by lchrusciel** [comment]
It's not that obvious, because Behat folder should be loaded in order to reuse defined steps. Rest could be excluded.

**Comment by mmenozzi** [comment]
Yeah you’re right. Didn’t thought about that.
