### ISSUE TITLE
phpstan-shim vs phpstan

### ISSUE THREAD

**Issue by loevgaard** [Sylius/PluginSkeleton#177]
Why is the plugin skeleton using the shim version of phpstan instead of just `phpstan/phpstan`?

**Comment by oallain** [comment]
Hi,

I think it's historic.
Since version 0.12 it is directly integrated into `phpstan/phpstan` :smile:

**Comment by Zales0123** [comment]
Indeed, however, we still have in `composer.json` - we should probably delete it 💃

**Comment by pamil** [comment]
Looksa a bit outdated, fixed by #182 and v1.7.5 for sure does not include phpstan-shim 🎉
