### ISSUE TITLE
Sylius version break front

### ISSUE THREAD

**Issue by oallain** [Sylius/PluginSkeleton#181]
Hello,

Actualy, in the PluginSkeleton we have dependency (in composer.json) `"sylius/sylius": "dev-master"` which is incompatible with the code in `tests/Application`.

$ yarn build

> ...
> 'buildShop' errored after 2 s
> Error in plugin 'gulp-chug'
> ...

We have two solutions:
1) fix the version of sylius to 1.6.*
2) Update the test application to take Sylius changes into account. For exemple changes into `package.json` fix errors in `yarn build`.

What do you think about that?

**Comment by lchrusciel** [comment]
IMO PluginSkeleton should be upgraded to the newest stable version.
