### ISSUE TITLE
Mapping error on fresh install

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/PluginSkeleton#201]
I have the error below on fresh install:

Uncaught Doctrine\ORM\Mapping\MappingException: Cannot find a field on 'Sylius\Component\Core\Model\ChannelPricing' that is mapped to column 'channelCode'. Either the field does not exist or an association exists but it has multiple join columns.

**Comment by pptasinski-bitbag** [comment]
Hi - it is related to bug with doctrine-brige. Try to restrict version to <4.4.16 for this package and it should work.

**Comment by SylvanoTombo** [comment]
Hi..Thanks

**Comment by lchrusciel** [comment]
According to https://github.com/symfony/symfony/issues/38861 4.4.17 should be fine again
