### ISSUE TITLE
Plugin install/uninstall 

### ISSUE THREAD

**Issue by Snake-Tn** [Sylius/PluginSkeleton#25]
It's a common use case to install/uninstall plugins for any e-commerce plateforme.

If I create a plugin which require to extend the DB schema by new columns/tables, how can I tell my customers to install this plugin: there should be simple and unique procedure to apply on all Sylius plugins.

I don't think I should ask them to exec `app/console doctrine:schema:update --force`

Same question: how can I guide them to uninstall it?

Magento2 for example, offers a command to enable/disable + install/uninstall plugins.
Also it gives plugin developers a clear interface to write install/uninstall scripts (similar to doctrine migrations)

**Comment by pjedrzejewski** [comment]
Currently, Sylius plugins are not meant to be installed by end users, but by devs. Of course, somewhere in the future it might be interesting to implement this functionality too.

**Comment by pamil** [comment]
The process with Symfony is that we always need to recompile the container so that plugin installation should be done by a developer.
