### ISSUE TITLE
FOSOAuthServerBundle not compatible with Sylius 1.9 when requiring Symfony ^4.4

### ISSUE THREAD

**Issue by Prometee** [Sylius/PluginSkeleton#254]
Using the `1.9` branch of this repository, I get this kind of errors

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
  The service "fos_oauth_server.controller.authorize" has a dependency on a non-existent service "templating".  
```
Example : https://github.com/FLUX-SE/SyliusPayumStripePlugin/runs/2044287962?check_suite_focus=true

Anyone succeeded to require Symfony 4.4 while installing Sylius 1.9 ?

**Comment by bigboss86** [comment]
Hi @Prometee. You need to require-dev the package:

`"friendsofsymfony/oauth-server-bundle": "^1.6 || >2.0.0-alpha.0 ^2.0@dev"`

**Comment by Prometee** [comment]
Thank you @bigboss86 this will be ok for Sylius 1.9 with Symfony 5.2 but not when using Symfony 4.4, here is the PR I made to fix the actual problem https://github.com/Sylius/PluginSkeleton/pull/255

**Comment by bigboss86** [comment]
It has worked for me. Do you know why?
https://github.com/odiseoteam/SyliusVendorPlugin/runs/2132264172?check_suite_focus=true

**Comment by Prometee** [comment]
@bigboss86 I found why, I used `"prefer-stable": true,` making composer to choose `^1.6` instead of `>2.0.0-alpha.0`.

Thanks @bigboss86 to point it out 😉

Ping @vvasiloi, maybe it was the same for you.
