### ISSUE TITLE
"Channel could not be found!"

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/PluginSkeleton#26]
As soon as I'm trying to use the channel context anywhere and do XML / API testing on it (PHPUnit) I get the error that the Channel could not be found. I'm using the default fixtures and the skeleton application.

Is there a way I can set the single channel available in the fixtures as the one being used before I run the tests?

**Comment by pjedrzejewski** [comment]
Channel context should be only used in case of browser session IMO, so API should be stateless. (you should get the channel from url or param)

What's the use case?

**Comment by stefandoorn** [comment]
This is the use case: https://github.com/stefandoorn/sitemap-plugin/issues/2.

WIP PR (which fails): https://github.com/stefandoorn/sitemap-plugin/pull/14.

Basically I want to show the sitemap specific for this channel, which is kind of a browser session (not really, but also not really an API stateless thing).

**Comment by stefandoorn** [comment]
This fixed it for me:

```
abstract class XmlApiTestCase extends ApiTestCase
{
    /**
     * @before
     */
    public function setUpClient()
    {
        $this->client = static::createClient();
        //$this->client = static::createClient(array(), array('HTTP_ACCEPT' => MediaTypes::XML));
    }
```

So probably the HTTP_ACCEPT triggers API style responses / requests :)

**Comment by stefandoorn** [comment]
Damn, cheered too quick. It didn't fix it.

**Comment by stefandoorn** [comment]
The issue is that using `pdo_sqlite` my database gets wiped before each test and therefore I was missing channels. The weird thing is, with `pdo_mysql` that doesn't happen, while the ORMPurger is still being called. I'm not sure how this can happen, but it happens in the phpunit tests from the sitemap-plugin mentioned above.
