### ISSUE TITLE
Gulp does not include shop and admin assets

### ISSUE THREAD

**Issue by bitbager** [Sylius/PluginSkeleton#27]
Running `$ yarn run gulp` does not parse ShopBundle and AdminBundle private files. This may be related to invalid path configuration in Gulpfile in `tests/Application`.

**Comment by pamil** [comment]
That's a tricky one, might be also related to the hacky way we set up the integration (`node_modules` symbolic link in the repository root).

**Comment by bitbager** [comment]
Yeap, this looks weird. Some of the assets are included, but some are not. If that helps - here's an example of how the admin panel looks like. After logging in, the menu bar is also inaccessible. Looks like some specific assets are missing, maybe there's something wrong with SemanticUI version?

![screen shot 2017-09-18 at 21 18 41](https://user-images.githubusercontent.com/28542010/30560076-0d8d6d60-9cb7-11e7-9ddd-cdbb587ddb8d.jpg)

**Comment by pamil** [comment]
Created #44 to make it testable.
