### ISSUE TITLE
MockerContainer not found

### ISSUE THREAD

**Issue by bigboss86** [Sylius/PluginSkeleton#301]
Hi, I have this error when try to install it:

`Uncaught Error: Class 'PSS\SymfonyMockerContainer\DependencyInjection\MockerContainer' not found`

**Comment by jakubtobiasz** [comment]
Hi!
I've opened the PR fixing this problem #300. You can fix this problem locally e.g. by running `composer require polishsymfonycommunity/symfony-mocker-container --dev`.

**Comment by lchrusciel** [comment]
Should be already fixed with https://github.com/Sylius/Sylius/releases/tag/v1.10.7. But #300 will help as well.
