### ISSUE TITLE
API Path is wrong in config

### ISSUE THREAD

**Issue by TheDevilOnLine** [Sylius/PluginSkeleton#310]
The behat tests that come with Sylius expect the new API to be at `/api/v2` but the configs at `tests/Application/config/sylius/1.10/packages/security.yml` still point to `/new-api` through the setting `parameters.sylius.security.new_api_route`.

Also all the other settings don't match up with the 1.10 behat tests (for example logging in as an admin, or using the API as a user). Basically the whole security.yaml file should be replaced by the default config.

**Comment by diimpp** [comment]
Current [security.yaml](https://github.com/Sylius/PluginSkeleton/blob/1.12/tests/Application/config/packages/security.yaml) for 1.11 and 1.12 is up to date, so according to sylius [release cycle](https://docs.sylius.com/en/latest/book/organization/release-cycle.html?highlight=release#supported-versions) 1.10 is no longer supported, so I'm going to close it for now.

Let's re-open of issue persists on 1.11 or 1.12.
