### ISSUE TITLE
Twig_Error_Runtime > Channel could not be found! on my first server:run

### ISSUE THREAD

**Issue by waqarmuneer** [Sylius/PluginSkeleton#35]
Hello, I'm not able to run the skeleton. when I do:
`php bin/console server:run --env=dev --docroot=/path/to/MyPlug/tests/Application/web`
I got error:
**
ChannelNotFoundException Twig_Error_Runtime
HTTP 500 Internal Server Error

An exception has been thrown during the rendering of a template ("Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.").**

**Comment by pamil** [comment]
This skeleton does not contain any fixtures, so it's an intended behaviour. It's meant to provide a starting point for writing a new plugin with test environment set up (Behat, PhpUnit, phpspec). 

Anyway, you can set up fixtures using `tests/Application/bin/console sylius:fixtures:load`.

**Comment by pamil** [comment]
Docs updated in #47.
