### ISSUE TITLE
The service "sylius.fixture.order" has a dependency on a non-existent service "sylius_abstraction.state_machine"

### ISSUE THREAD

**Issue by Dev-patel1882** [Sylius/PluginSkeleton#411]
**The service "sylius.fixture.order" has a dependency on a non-existent service "sylius_abstraction.state_machine".**

When I'm setting up the Sylius plugin skeleton, I'm facing this error. I've created plugin skeletons before, but this error didn't appear earlier. I think it might be a bug.

The error "**The service 'sylius.fixture.order' has a dependency on a non-existent service 'sylius_abstraction.state_machine**'" is preventing me from running any PHP commands.

![Screenshot from 2024-04-30 12-08-25](https://github.com/Sylius/PluginSkeleton/assets/128371272/16f113e1-c788-4dd5-83a3-a2aa610355a6)

**Comment by diimpp** [comment]
Related https://github.com/Sylius/Sylius-Standard/issues/976

**Comment by Prometee** [comment]
@Dev-patel1882, you can simply add the missing bundle to the file `tests/Application/config/bundles.php` : 
https://github.com/Sylius/PluginSkeleton/blob/1.12/tests/Application/config/bundles.php
The missing bundle is this one :
https://github.com/Sylius/Sylius-Standard/blob/1.13/config/bundles.php#L9

**Comment by Dev-patel1882** [comment]
Thanks, @Prometee , it works.
