### ISSUE TITLE
FatalThrowableError @ http://localhost:8000/dynamic-welcome

### ISSUE THREAD

**Issue by waqarmuneer** [Sylius/PluginSkeleton#49]
Hi, I tried latest skeleton setup and followed all given instruction. When I tried dynamic route :
http://localhost:8000/dynamic-welcome
or http://localhost:8000/dynamic-welcome/waqar
I got following exception:
(1/1) FatalThrowableError      Type  error: Argument 1 passed to  FOS\RestBundle\Controller\ExceptionController::__construct() must be an  instance of FOS\RestBundle\View\ViewHandlerInterface, none given, called  in  /home/waqar/mydev/salesperson/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php  on line 202

 Please guide for this.

**Comment by pamil** [comment]
Can't reproduce this issue, can you provide more information on try once again with a clean, most recent PluginSkeleton?

**Comment by waqarmuneer** [comment]
@pamil I have just tried most recent PluginSkeleton and performed all installation steps. I was looking at the route defined in (MyPlugin/src/Resources/config/app/shop_routing.yml) where "/static-welcome/{name}" works perfectly in browser and "/dynamic-welcome/{name}" is not working. 
Like http://localhost:8000/static-welcome/sylius  is working
and http://localhost:8000/dynamic-welcome/sylius is not working

**Comment by pamil** [comment]
Could you please open a new issue if that's still a case? I believe we have solved it somewhere along the way.
