### ISSUE TITLE
Add PHPSpec and PHPUnit to travis.yml

### ISSUE THREAD

**Issue by bitbager** [Sylius/PluginSkeleton#55]
Isn't it a good idea to have PHPSpec and PHPUnit by default in the travis.yml build file?

**Comment by lchrusciel** [comment]
👍  Could you open a PR?

**Comment by bitbager** [comment]
Sure. I will do it once I get a minute 🙂

**Comment by GSadee** [comment]
I guess this PR can be close after #64 was merged.
