### ISSUE TITLE
Problems while overriding the resource

### ISSUE THREAD

**Issue by bitbager** [Sylius/PluginSkeleton#58]
Trying to override a custom entity resource in the plugin with the docs-recommended way causes table exists Doctrine error. Here's the use case - https://github.com/BitBagCommerce/SyliusCmsPlugin/issues/36.

**Comment by bitbager** [comment]
Can we discuss this issue? It's actually important to make the plugins flexible and allow overriding models in them 🙂

**Comment by pamil** [comment]
Solution's here: https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/110
