### ISSUE TITLE
Use Model instead of Entity namespace for Doctrine mapping

### ISSUE THREAD

**Issue by bitbager** [Sylius/PluginSkeleton#61]
Currently, the plugin does not allow to use Model namespace for Doctrine models. Following this Sylius standard in it would be nice.

**Comment by bitbager** [comment]
I'd suggest adding the `getModelNamespace` or even `useModelNamespace(): bool`. The second approach will let the user decide if he wants to use `Model` namespace or go for the `Entity` approach.

**Comment by lchrusciel** [comment]
The difference is, that entity is a default folder in Symfony related apps. Model is used in sylius components because they are framework agnostic

**Comment by bitbager** [comment]
Yeap, but how about we let the user decide which namespace to use?

**Comment by pamil** [comment]
Let's continue the discussion in #93.
