### ISSUE TITLE
Testing plugin at end user - Behat

### ISSUE THREAD

**Issue by smtlab** [Sylius/PluginSkeleton#88]
Let's assume I am working on SyliusWalletPlugin which extends user to have wallet feature as follows

In my plugin, I have defined interface and walletableTrait

````
UserWalletInterface extends UserInterface
{
  public function getWallet();
}
````
Now the end user who uses the plugin needs to implement UserWalletInterface and include wallatable trait.

Now how one can do Behat scenario testing which doesn't have a working User class which can only be implemented at the end user.

**Comment by lchrusciel** [comment]
Just create a working class inside of test folder. It will also work as a sample integration :)
