### ISSUE TITLE
Allow Model namespace

### ISSUE THREAD

**Issue by bitbager** [Sylius/PluginSkeleton#93]
Hi there!

Would it be possible to customize the `SyliusPluginTrait` so that it accepts `Model` namespace instead of `Entity` for Doctrine declarations?

**Comment by stefandoorn** [comment]
Can it be `Model` + `Entity` instead of only `Model`? Else I think a lot plugins needs to make BC adjustments, or am I missing something?

**Comment by lchrusciel** [comment]
I'm do not have too much against, but by default, we should use an `Entity`. Two problems tho:
1. `SyliusPluginTrait` is a part of a core, so the issue should be opened to the main repository
2. Is it needed? It seems it is pretty straightforward to change the folder only for your project. I would prefer to have `SyliusPluginTrait` as small as possible to not fight with Symfony in the longer term.

**Comment by pamil** [comment]
That was something I also came onto when developing a new plugin, it's a bit counterintuitive if you are used to Sylius application with Model namespace.

**Comment by igormukhingmailcom** [comment]
To use `Model` at your plugin - you can extend it from `AbstractResourceBundle` (see `getModelNamespace`).

```
<?php

use Sylius\Bundle\CoreBundle\Application\SyliusPluginTrait;
use Sylius\Bundle\ResourceBundle\AbstractResourceBundle;

final class YourSyliusPlugin extends AbstractResourceBundle
{
    use SyliusPluginTrait;
}
```

**Comment by diimpp** [comment]
Seems to be solved and can be closed
